#!/usr/bin/env python3
"""Generate the bounded R1033 assignment-statement policy."""

from pathlib import Path
import re
import sys


def main() -> int:
    source = Path(sys.argv[1]).read_text(encoding="utf-8").strip()
    match = re.fullmatch(
        r"\(schema frontend-assignment-policy-v0\s+"
        r"\(policy assignment-stmt assignment-stmt (R\d+)\)\s+"
        r"\(token assignment (=)\)\s+"
        r"\(variable-expression (variable) (R\d+) (R\d+) (R\d+)\)\s+"
        r"\(expression integer-literal (R\d+)\)\s+"
        r"\(binary-expression (add) (R\d+) (R\d+) (1) (2) (\+)\)\s+"
        r"\(binary-expression (subtract) (R\d+) (R\d+) (5) (3) (–)\)\s+"
        r"\(binary-expression (multiply) (R\d+) (R\d+) (2) (3) (\*)\)\s+"
        r"\(binary-expression (divide) (R\d+) (R\d+) (6) (2) (/)\)\s+"
        r"\(sequence (two-assignment) (assignment-stmt) (assignment-stmt)\)\s+"
        r"\(literal-range integer-literal (-?\d+) (-?\d+)\)\)", source
    )
    if match is None:
        raise SystemExit("invalid assignment policy schema")
    output = Path(sys.argv[2])
    output.mkdir(parents=True, exist_ok=True)
    rows = [
        ("integer-literal", match.group(7), "", match.group(1), "", "", "", ""),
        (match.group(8), match.group(9), match.group(10), match.group(1),
            f"{match.group(11)} {match.group(13)} {match.group(12)}", match.group(11),
            match.group(12), match.group(13)),
        ("subtract", match.group(15), match.group(16), match.group(1),
            f"{match.group(17)} {match.group(19)} {match.group(18)}", match.group(17),
            match.group(18), match.group(19)),
        ("multiply", match.group(21), match.group(22), match.group(1),
            f"{match.group(23)} {match.group(25)} {match.group(24)}", match.group(23),
            match.group(24), match.group(25)),
        ("divide", match.group(27), match.group(28), match.group(1),
            f"{match.group(29)} {match.group(31)} {match.group(30)}", match.group(29),
            match.group(30), match.group(31)),
    ]
    row_text = "\n".join(
        "        assignment_policy_row_t('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')%s" % (
            *row, ", &" if index < len(rows) - 1 else ""
        )
        for index, row in enumerate(rows)
    )
    (output / "frontend_assignment_policy_generated.f90").write_text(
        "! Generated by tools/generate_assignment_policy.py. Origin: MECHANICAL.\n"
        "module frontend_assignment_policy_generated\n"
        "    implicit none\n"
        "    private\n"
        "    character(len=*), parameter, public :: assignment_policy_lhs = 'assignment-stmt'\n"
        f"    character(len=*), parameter, public :: assignment_policy_source_rule = '{match.group(1)}'\n"
        "    character(len=*), parameter, public :: assignment_policy_operator = '='\n"
        f"    character(len=*), parameter, public :: assignment_policy_variable_expression_kind = '{match.group(3)}'\n"
        f"    character(len=*), parameter, public :: assignment_policy_variable_expression_rule = '{match.group(4)}'\n"
        f"    character(len=*), parameter, public :: assignment_policy_variable_designator_rule = '{match.group(5)}'\n"
        f"    character(len=*), parameter, public :: assignment_policy_variable_name_rule = '{match.group(6)}'\n"
        "    character(len=*), parameter, public :: assignment_policy_variable_name = 'x'\n"
        "    character(len=*), parameter, public :: assignment_policy_integer_literal_rule = &\n"
        f"        '{match.group(7)}'\n"
        f"    character(len=*), parameter, public :: assignment_policy_sequence_name = '{match.group(32)}'\n"
        "    integer, parameter, public :: assignment_policy_sequence_count = 2\n"
        "    type, public :: assignment_policy_sequence_row_t\n"
        "        character(len=32) :: name\n"
        "        character(len=32) :: first_record\n"
        "        character(len=32) :: second_record\n"
        "    end type assignment_policy_sequence_row_t\n"
        "    type(assignment_policy_sequence_row_t), parameter, public :: &\n"
        "        assignment_policy_sequence_rows(1) = [ &\n"
        f"        assignment_policy_sequence_row_t('{match.group(32)}', '{match.group(33)}', '{match.group(34)}') &\n"
        "        ]\n"
        f"    integer, parameter, public :: assignment_policy_integer_literal_min = {match.group(35)}\n"
        f"    integer, parameter, public :: assignment_policy_integer_literal_max = {match.group(36)}\n"
        "    type, public :: assignment_policy_row_t\n"
        "        character(len=16) :: expression_kind\n"
        "        character(len=16) :: expression_rule\n"
        "        character(len=16) :: operator_rule\n"
        "        character(len=16) :: source_rule\n"
        "        character(len=32) :: source_spelling\n"
        "        character(len=16) :: left_operand\n"
        "        character(len=16) :: right_operand\n"
        "        character(len=8) :: operator\n"
        "    end type assignment_policy_row_t\n"
        "    character(len=*), parameter, public :: assignment_policy_variable_expression_row = &\n"
        f"        'variable {match.group(4)} {match.group(5)} {match.group(6)}'\n"
        "    type(assignment_policy_row_t), parameter, public :: assignment_policy_rows(5) = [ &\n"
        f"{row_text} &\n"
        "        ]\n"
        "    integer, parameter, public :: assignment_policy_row_count = 5\n"
        "    integer, parameter, public :: assignment_policy_source_page = 155\n"
        "end module frontend_assignment_policy_generated\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
