#!/usr/bin/env python3
"""Generate the bounded program-envelope token table from its SX source."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


TOKEN = re.compile(r"\(token\s+([a-z][a-z0-9-]*)\s+([a-z][a-z0-9-]*)\)")
SCHEMA = re.compile(r"\(schema\s+([a-z][a-z0-9-]*)\s+(.*?)\)\s*\Z", re.S)


def parse(source: str) -> list[tuple[str, str]]:
    match = SCHEMA.fullmatch(source.strip())
    if match is None or match.group(1) != "frontend-program-envelope-v0":
        raise ValueError("invalid program-envelope schema")
    tokens = TOKEN.findall(match.group(2))
    if len(tokens) != 3 or len(set(name for name, _ in tokens)) != len(tokens):
        raise ValueError("program-envelope schema must contain three unique tokens")
    if {name for name, _ in tokens} != {
        "header-keyword",
        "terminator-keyword",
        "terminator-kind",
    }:
        raise ValueError("program-envelope schema has unexpected token names")
    if dict(tokens) != {
        "header-keyword": "program",
        "terminator-keyword": "end",
        "terminator-kind": "program",
    }:
        raise ValueError("program-envelope schema contains unexpected token values")
    return tokens


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render(tokens: list[tuple[str, str]]) -> str:
    constants = {
        name.replace("-", "_"): index
        for index, (name, _) in enumerate(tokens, start=1)
    }
    lines = [
        "! Generated by tools/generate_program_envelope.py. Origin: MECHANICAL.",
        "module frontend_program_envelope_generated",
        "    implicit none",
        "    private",
        "",
        "    integer, parameter, public :: program_envelope_header_keyword = %d" % constants["header_keyword"],
        "    integer, parameter, public :: program_envelope_terminator_keyword = %d" % constants["terminator_keyword"],
        "    integer, parameter, public :: program_envelope_terminator_kind = %d" % constants["terminator_kind"],
        "",
        "    type, public :: program_envelope_token_t",
        "        character(len=32) :: text = ''",
        "    end type program_envelope_token_t",
        "",
        "    type(program_envelope_token_t), parameter, public :: &",
        "        program_envelope_token_table(3) = [ &",
    ]
    for index, (_, value) in enumerate(tokens):
        comma = ", &" if index < len(tokens) - 1 else " ]"
        lines.append("        program_envelope_token_t(%s)%s" % (quote(value), comma))
    lines += [
        "",
        "    public :: program_envelope_token_matches",
        "",
        "contains",
        "",
        "    logical function program_envelope_token_matches(slot, token)",
        "        integer, intent(in) :: slot",
        "        character(len=*), intent(in) :: token",
        "",
        "        program_envelope_token_matches = .false.",
        "        if (slot < 1 .or. slot > size(program_envelope_token_table)) return",
        "        program_envelope_token_matches = lowercase(trim(token)) == &",
        "            lowercase(trim(program_envelope_token_table(slot)%text))",
        "    end function program_envelope_token_matches",
        "",
        "    pure function lowercase(input) result(output)",
        "        character(len=*), intent(in) :: input",
        "        character(len=len(input)) :: output",
        "        integer :: index, code",
        "",
        "        output = input",
        "        do index = 1, len(input)",
        "            code = iachar(output(index:index))",
        "            if (code >= iachar('A') .and. code <= iachar('Z')) &",
        "                output(index:index) = achar(code + iachar('a') - iachar('A'))",
        "        end do",
        "    end function lowercase",
        "",
        "end module frontend_program_envelope_generated",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("schema", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        generated = render(parse(args.schema.read_text(encoding="utf-8")))
    except (OSError, ValueError) as error:
        parser.error(str(error))
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "frontend_program_envelope_generated.f90").write_text(
        generated, encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
