#!/usr/bin/env python3
"""Generate the bounded program-envelope tables and R501 witness."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


TOKEN = re.compile(r"\(token\s+([a-z][a-z0-9-]*)\s+([a-z][a-z0-9-]*)\)")
POLICY = re.compile(
    r"\(policy\s+([a-z][a-z0-9-]*)\s+([a-z][a-z0-9-]*)\s+"
    r"([a-z][a-z0-9-]*)\s+([a-z][a-z0-9-]*)\)"
)
WITNESS = re.compile(r"\(witness\s+([a-z][a-z0-9-]*)\s+([^\s()]+)\)")
SCHEMA = re.compile(r"\(schema\s+([a-z][a-z0-9-]*)\s+(.*?)\)\s*\Z", re.S)


def parse(source: str) -> tuple[
    list[tuple[str, str]], list[tuple[str, str, str, str]], dict[str, str]
]:
    match = SCHEMA.fullmatch(source.strip())
    if match is None or match.group(1) != "frontend-program-envelope-v0":
        raise ValueError("invalid program-envelope schema")
    body = match.group(2)
    tokens = TOKEN.findall(body)
    if len(tokens) != 3 or len(set(name for name, _ in tokens)) != len(tokens):
        raise ValueError("program-envelope schema must contain three unique tokens")
    if {name for name, _ in tokens} != {
        "header-keyword", "terminator-keyword", "terminator-kind",
    }:
        raise ValueError("program-envelope schema has unexpected token names")
    if dict(tokens) != {
        "header-keyword": "program", "terminator-keyword": "end",
        "terminator-kind": "program",
    }:
        raise ValueError("program-envelope schema contains unexpected token values")
    policies = POLICY.findall(body)
    if policies != [
        ("program", "program", "end", "program"),
        ("module", "module", "end", "module"),
        ("subroutine", "subroutine", "end", "subroutine"),
        ("function", "function", "end", "function"),
    ]:
        raise ValueError("program-envelope schema has an invalid bounded policy table")
    witness = dict(WITNESS.findall(body))
    if set(witness) != {
        "id", "lhs", "origin", "resolution", "document", "clause", "rule",
        "page", "source-hash",
    }:
        raise ValueError("program-envelope schema has incomplete witness")
    if witness["id"] != "R501" or witness["lhs"] != "program":
        raise ValueError("program-envelope schema contains unexpected witness")
    if witness["page"] != "53":
        raise ValueError("program-envelope schema contains unexpected witness page")
    return tokens, policies, witness


def quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def render(
    tokens: list[tuple[str, str]],
    policies: list[tuple[str, str, str, str]],
    witness: dict[str, str],
) -> str:
    constants = {
        name.replace("-", "_"): index
        for index, (name, _) in enumerate(tokens, start=1)
    }
    witness_strings = ", ".join(
        quote(witness[key]) for key in (
            "id", "lhs", "origin", "resolution", "document", "clause", "rule",
        )
    )
    lines = [
        "! Generated by tools/generate_program_envelope.py. Origin: MECHANICAL.",
        "module frontend_program_envelope_generated",
        "    use, intrinsic :: iso_fortran_env, only: int64",
        "    implicit none",
        "    private",
        "",
        "    integer, parameter, public :: program_envelope_header_keyword = %d" % constants["header_keyword"],
        "    integer, parameter, public :: program_envelope_terminator_keyword = %d" % constants["terminator_keyword"],
        "    integer, parameter, public :: program_envelope_terminator_kind = %d" % constants["terminator_kind"],
        "",
        "    type, public :: program_envelope_token_t",
        "        character(len=32) :: text = ''",
        "    end type program_envelope_token_t",
        "",
        "    type(program_envelope_token_t), parameter, public :: &",
        "        program_envelope_token_table(3) = [ &",
    ]
    for index, (_, value) in enumerate(tokens):
        comma = ", &" if index < len(tokens) - 1 else " ]"
        lines.append("        program_envelope_token_t(%s)%s" % (quote(value), comma))
    lines += [
        "",
        "    type, public :: program_envelope_policy_t",
        "        character(len=32) :: kind = ''",
        "        character(len=32) :: header = ''",
        "        character(len=32) :: terminator_keyword = ''",
        "        character(len=32) :: terminator_kind = ''",
        "    end type program_envelope_policy_t",
        "",
        "    type(program_envelope_policy_t), parameter, public :: &",
        "        program_envelope_policy_table(%d) = [ &" % len(policies),
    ]
    for index, policy in enumerate(policies):
        comma = ", &" if index < len(policies) - 1 else " ]"
        lines.append("        program_envelope_policy_t(%s)%s" % (
            ", ".join(quote(value) for value in policy), comma
        ))
    lines += [
        "",
        "    type, public :: program_envelope_witness_t",
        "        character(len=64) :: id = ''",
        "        character(len=64) :: lhs = ''",
        "        character(len=32) :: origin = ''",
        "        character(len=32) :: resolution = ''",
        "        character(len=128) :: document = ''",
        "        character(len=64) :: clause = ''",
        "        character(len=64) :: rule = ''",
        "        integer(int64) :: page = 0_int64",
        "        character(len=128) :: source_hash = ''",
        "    end type program_envelope_witness_t",
        "",
        "    type(program_envelope_witness_t), parameter, public :: &",
        "        program_envelope_program_witness = program_envelope_witness_t( &",
        "        %s, %s_int64, %s)" % (
            witness_strings, witness["page"], quote(witness["source-hash"]),
        ),
        "",
        "    public :: program_envelope_policy_lookup",
        "    public :: program_envelope_policy_matches",
        "    public :: program_envelope_token_matches",
        "",
        "contains",
        "",
        "    logical function program_envelope_policy_lookup(token, policy_index, kind)",
        "        character(len=*), intent(in) :: token",
        "        integer, intent(out) :: policy_index",
        "        character(len=*), intent(out) :: kind",
        "        integer :: index",
        "",
        "        policy_index = 0",
        "        kind = ''",
        "        do index = 1, size(program_envelope_policy_table)",
        "            if (lowercase(trim(token)) == lowercase(trim(program_envelope_policy_table(index)%header))) then",
        "                policy_index = index",
        "                kind = program_envelope_policy_table(index)%kind",
        "                program_envelope_policy_lookup = .true.",
        "                return",
        "            end if",
        "        end do",
        "        program_envelope_policy_lookup = .false.",
        "    end function program_envelope_policy_lookup",
        "",
        "    logical function program_envelope_policy_matches(policy_index, slot, token)",
        "        integer, intent(in) :: policy_index",
        "        integer, intent(in) :: slot",
        "        character(len=*), intent(in) :: token",
        "",
        "        program_envelope_policy_matches = .false.",
        "        if (policy_index < 1) return",
        "        if (policy_index > size(program_envelope_policy_table)) return",
        "        if (slot == 1) then",
        "            program_envelope_policy_matches = lowercase(trim(token)) == &",
        "                lowercase(trim(program_envelope_policy_table(policy_index)%header))",
        "        else if (slot == 2) then",
        "            program_envelope_policy_matches = lowercase(trim(token)) == &",
        "                lowercase(trim(program_envelope_policy_table(policy_index)%terminator_keyword))",
        "        else if (slot == 3) then",
        "            program_envelope_policy_matches = lowercase(trim(token)) == &",
        "                lowercase(trim(program_envelope_policy_table(policy_index)%terminator_kind))",
        "        end if",
        "    end function program_envelope_policy_matches",
        "",
        "    logical function program_envelope_token_matches(slot, token)",
        "        integer, intent(in) :: slot",
        "        character(len=*), intent(in) :: token",
        "",
        "        program_envelope_token_matches = .false.",
        "        if (slot < 1 .or. slot > size(program_envelope_token_table)) return",
        "        program_envelope_token_matches = lowercase(trim(token)) == &",
        "            lowercase(trim(program_envelope_token_table(slot)%text))",
        "    end function program_envelope_token_matches",
        "",
        "    pure function lowercase(input) result(output)",
        "        character(len=*), intent(in) :: input",
        "        character(len=len(input)) :: output",
        "        integer :: index, code",
        "",
        "        output = input",
        "        do index = 1, len(input)",
        "            code = iachar(output(index:index))",
        "            if (code >= iachar('A') .and. code <= iachar('Z')) &",
        "                output(index:index) = achar(code + iachar('a') - iachar('A'))",
        "        end do",
        "    end function lowercase",
        "",
        "end module frontend_program_envelope_generated",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("schema", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        generated = render(*parse(args.schema.read_text(encoding="utf-8")))
    except (OSError, ValueError) as error:
        parser.error(str(error))
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "frontend_program_envelope_generated.f90").write_text(
        generated, encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
