#!/usr/bin/env python3
"""Generate the bounded R1162/R1164 STOP 7 policy."""

from __future__ import annotations

import re
import sys
from pathlib import Path


def main() -> int:
    source = Path(sys.argv[1]).read_text(encoding="utf-8").strip()
    match = re.fullmatch(
        r"\(schema frontend-stop-policy-v0\s+"
        r"\(statement (stop-stmt) (stop-stmt) (R\d+)\)\s+"
        r"\(stop-code (integer-literal) (R\d+) (7)\)\s+"
        r"\(source (J3-24-007) (\d+) (214) ([^\s()]+)\)\)",
        source,
    )
    if match is None:
        raise SystemExit("invalid stop policy schema")
    _, statement_kind, statement_rule, code_kind, code_rule, code, document, clause, page, source_hash = (
        match.groups()
    )
    output = Path(sys.argv[2])
    output.mkdir(parents=True, exist_ok=True)
    (output / "frontend_stop_policy_generated.f90").write_text(
        "! Generated by tools/generate_stop_policy.py. Origin: MECHANICAL.\n"
        "module frontend_stop_policy_generated\n"
        "    use, intrinsic :: iso_fortran_env, only: int64\n"
        "    implicit none\n"
        "    private\n\n"
        f"    character(len=*), parameter, public :: stop_policy_statement_kind = '{statement_kind}'\n"
        f"    character(len=*), parameter, public :: stop_policy_statement_rule = '{statement_rule}'\n"
        f"    character(len=*), parameter, public :: stop_policy_code_kind = '{code_kind}'\n"
        f"    character(len=*), parameter, public :: stop_policy_code_rule = '{code_rule}'\n"
        f"    integer(int64), parameter, public :: stop_policy_code = {code}_int64\n"
        f"    character(len=*), parameter, public :: stop_policy_document = '{document}'\n"
        f"    character(len=*), parameter, public :: stop_policy_clause = '{clause}'\n"
        f"    integer(int64), parameter, public :: stop_policy_page = {page}_int64\n"
        f"    character(len=*), parameter, public :: stop_policy_source_hash = '{source_hash}'\n"
        "end module frontend_stop_policy_generated\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
