#!/usr/bin/env python3
"""Generate the bounded, source-backed PRINT *, 7[, 8[, 9[, 10[, 11[, 12]]]]] typed AST policy."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


SCHEMA = re.compile(
    r"\(schema frontend-print-policy-v0\s+"
    r"\(statement (print-stmt) (PRINT) (R\d+)\)\s+"
    r"\(format (default-char-expr) (\*) (R\d+)\)\s+"
    r"\(output-item (integer-literal) (7) (R\d+)\)\s+"
    r"\(output-item (integer-literal) (8) (R\d+)\)\s+"
    r"\(output-item (integer-literal) (9) (R\d+)\)\s+"
    r"\(output-item (integer-literal) (10) (R\d+)\)\s+"
    r"\(output-item (integer-literal) (11) (R\d+)\)\s+"
    r"\(output-item (integer-literal) (12) (R\d+)\)\s+"
    r"\(source (J3-24-007) ([^\s()]+) ([^\s()]+) ([^\s()]+) "
    r"(242) (244) (248) ([^\s()]+)\)\)"
)


def render(source: str) -> str:
    match = SCHEMA.fullmatch(source.strip())
    if match is None:
        raise ValueError("invalid print policy schema")
    (
        statement_kind, statement_token, statement_rule, format_kind, format_value,
        format_rule, output_kind, output_value, output_rule, output_2_kind,
        output_2_value, output_2_rule, output_3_kind, output_3_value, output_3_rule,
        output_4_kind, output_4_value, output_4_rule,
        output_5_kind, output_5_value, output_5_rule,
        output_6_kind, output_6_value, output_6_rule,
        document,
        statement_clause, format_clause, output_clause, statement_page,
        format_page, output_page, source_hash,
    ) = match.groups()
    return f'''! Generated by tools/generate_print_policy.py. Origin: MECHANICAL.
module frontend_print_policy_generated
    use, intrinsic :: iso_fortran_env, only: int64
    use frontend_ast_v1_generated, only: source_span_t, source_span_validate, source_span_to_sx
    implicit none
    private

    character(len=*), parameter, public :: print_policy_statement_kind = '{statement_kind}'
    character(len=*), parameter, public :: print_policy_statement_token = '{statement_token}'
    character(len=*), parameter, public :: print_policy_statement_rule = '{statement_rule}'
    character(len=*), parameter, public :: print_policy_format_kind = '{format_kind}'
    character(len=*), parameter, public :: print_policy_format_value = '{format_value}'
    character(len=*), parameter, public :: print_policy_format_rule = '{format_rule}'
    character(len=*), parameter, public :: print_policy_output_kind = '{output_kind}'
    integer(int64), parameter, public :: print_policy_output_value = {output_value}_int64
    character(len=*), parameter, public :: print_policy_output_rule = '{output_rule}'
    character(len=*), parameter, public :: print_policy_output_2_kind = '{output_2_kind}'
    integer(int64), parameter, public :: print_policy_output_2_value = {output_2_value}_int64
    character(len=*), parameter, public :: print_policy_output_2_rule = '{output_2_rule}'
    character(len=*), parameter, public :: print_policy_output_3_kind = '{output_3_kind}'
    integer(int64), parameter, public :: print_policy_output_3_value = {output_3_value}_int64
    character(len=*), parameter, public :: print_policy_output_3_rule = '{output_3_rule}'
    character(len=*), parameter, public :: print_policy_output_4_kind = '{output_4_kind}'
    integer(int64), parameter, public :: print_policy_output_4_value = {output_4_value}_int64
    character(len=*), parameter, public :: print_policy_output_4_rule = '{output_4_rule}'
    character(len=*), parameter, public :: print_policy_output_5_kind = '{output_5_kind}'
    integer(int64), parameter, public :: print_policy_output_5_value = {output_5_value}_int64
    character(len=*), parameter, public :: print_policy_output_5_rule = '{output_5_rule}'
    character(len=*), parameter, public :: print_policy_output_6_kind = '{output_6_kind}'
    integer(int64), parameter, public :: print_policy_output_6_value = {output_6_value}_int64
    character(len=*), parameter, public :: print_policy_output_6_rule = '{output_6_rule}'
    character(len=*), parameter, public :: print_policy_document = '{document}'
    character(len=*), parameter, public :: print_policy_statement_clause = '{statement_clause}'
    character(len=*), parameter, public :: print_policy_format_clause = '{format_clause}'
    character(len=*), parameter, public :: print_policy_output_clause = '{output_clause}'
    integer(int64), parameter, public :: print_policy_statement_page = {statement_page}_int64
    integer(int64), parameter, public :: print_policy_format_page = {format_page}_int64
    integer(int64), parameter, public :: print_policy_output_page = {output_page}_int64
    character(len=*), parameter, public :: print_policy_source_hash = &
        '{source_hash}'

    type, public :: print_stmt_t
        character(len=32) :: format_kind = ''
        character(len=32) :: format_value = ''
        character(len=32) :: output_kind = ''
        integer(int64) :: output_value = 0_int64
        integer(int64) :: output_count = 0_int64
        character(len=32) :: output_2_kind = ''
        integer(int64) :: output_2_value = 0_int64
        character(len=32) :: output_3_kind = ''
        integer(int64) :: output_3_value = 0_int64
        character(len=32) :: output_4_kind = ''
        integer(int64) :: output_4_value = 0_int64
        character(len=32) :: output_5_kind = ''
        integer(int64) :: output_5_value = 0_int64
        character(len=32) :: output_6_kind = ''
        integer(int64) :: output_6_value = 0_int64
        type(source_span_t) :: span
        character(len=32) :: statement_rule = ''
        character(len=32) :: format_rule = ''
        character(len=32) :: output_rule = ''
        character(len=32) :: output_2_rule = ''
        character(len=32) :: output_3_rule = ''
        character(len=32) :: output_4_rule = ''
        character(len=32) :: output_5_rule = ''
        character(len=32) :: output_6_rule = ''
        character(len=128) :: source_document = ''
        character(len=32) :: statement_clause = ''
        character(len=32) :: format_clause = ''
        character(len=32) :: output_clause = ''
        character(len=32) :: output_2_clause = ''
        character(len=32) :: output_3_clause = ''
        character(len=32) :: output_4_clause = ''
        character(len=32) :: output_5_clause = ''
        character(len=32) :: output_6_clause = ''
        integer(int64) :: statement_page = 0_int64
        integer(int64) :: format_page = 0_int64
        integer(int64) :: output_page = 0_int64
        integer(int64) :: output_2_page = 0_int64
        integer(int64) :: output_3_page = 0_int64
        integer(int64) :: output_4_page = 0_int64
        integer(int64) :: output_5_page = 0_int64
        integer(int64) :: output_6_page = 0_int64
        character(len=128) :: source_hash = ''
    end type print_stmt_t

    public :: print_stmt_validate
    public :: print_stmt_to_sx

contains

    logical function print_stmt_validate(value, message)
        type(print_stmt_t), intent(in) :: value
        character(len=*), intent(out) :: message

        message = ''
        if (trim(value%format_kind) /= trim(print_policy_format_kind) .or. &
            trim(value%format_value) /= trim(print_policy_format_value) .or. &
            trim(value%output_kind) /= trim(print_policy_output_kind) .or. &
            value%output_value /= print_policy_output_value) then
            message = 'invalid-print-policy-value'
            print_stmt_validate = .false.
            return
        end if
        if (value%output_count < 1_int64 .or. value%output_count > 6_int64) then
            message = 'invalid-print-policy-output-count'
            print_stmt_validate = .false.
            return
        end if
        if (value%output_count >= 2_int64) then
            if (trim(value%output_2_kind) /= trim(print_policy_output_2_kind) .or. &
                value%output_2_value /= print_policy_output_2_value) then
                message = 'invalid-print-policy-value'
                print_stmt_validate = .false.
                return
            end if
            if (trim(value%output_2_rule) /= trim(print_policy_output_2_rule) .or. &
                trim(value%output_2_clause) /= trim(print_policy_output_clause) .or. &
                value%output_2_page /= print_policy_output_page) then
                message = 'invalid-print-policy-rule'
                print_stmt_validate = .false.
                return
            end if
        end if
        if (value%output_count == 3_int64) then
            if (trim(value%output_3_kind) /= trim(print_policy_output_3_kind) .or. &
                value%output_3_value /= print_policy_output_3_value) then
                message = 'invalid-print-policy-value'
                print_stmt_validate = .false.
                return
            end if
            if (trim(value%output_3_rule) /= trim(print_policy_output_3_rule) .or. &
                trim(value%output_3_clause) /= trim(print_policy_output_clause) .or. &
                value%output_3_page /= print_policy_output_page) then
                message = 'invalid-print-policy-rule'
                print_stmt_validate = .false.
                return
            end if
        end if
        if (value%output_count == 4_int64) then
            if (trim(value%output_4_kind) /= trim(print_policy_output_4_kind) .or. &
                value%output_4_value /= print_policy_output_4_value) then
                message = 'invalid-print-policy-value'
                print_stmt_validate = .false.
                return
            end if
            if (trim(value%output_4_rule) /= trim(print_policy_output_4_rule) .or. &
                trim(value%output_4_clause) /= trim(print_policy_output_clause) .or. &
                value%output_4_page /= print_policy_output_page) then
                message = 'invalid-print-policy-rule'
                print_stmt_validate = .false.
                return
            end if
        end if
        if (value%output_count == 5_int64) then
            if (trim(value%output_5_kind) /= trim(print_policy_output_5_kind) .or. &
                value%output_5_value /= print_policy_output_5_value) then
                message = 'invalid-print-policy-value'
                print_stmt_validate = .false.
                return
            end if
            if (trim(value%output_5_rule) /= trim(print_policy_output_5_rule) .or. &
                trim(value%output_5_clause) /= trim(print_policy_output_clause) .or. &
                value%output_5_page /= print_policy_output_page) then
                message = 'invalid-print-policy-rule'
                print_stmt_validate = .false.
                return
            end if
        end if
        if (value%output_count == 6_int64) then
            if (trim(value%output_6_kind) /= trim(print_policy_output_6_kind) .or. &
                value%output_6_value /= print_policy_output_6_value) then
                message = 'invalid-print-policy-value'
                print_stmt_validate = .false.
                return
            end if
            if (trim(value%output_6_rule) /= trim(print_policy_output_6_rule) .or. &
                trim(value%output_6_clause) /= trim(print_policy_output_clause) .or. &
                value%output_6_page /= print_policy_output_page) then
                message = 'invalid-print-policy-rule'
                print_stmt_validate = .false.
                return
            end if
        end if
        if (trim(value%statement_rule) /= trim(print_policy_statement_rule) .or. &
            trim(value%format_rule) /= trim(print_policy_format_rule) .or. &
            trim(value%output_rule) /= trim(print_policy_output_rule)) then
            message = 'invalid-print-policy-rule'
            print_stmt_validate = .false.
            return
        end if
        if (trim(value%source_document) /= trim(print_policy_document) .or. &
            trim(value%statement_clause) /= trim(print_policy_statement_clause) .or. &
            trim(value%format_clause) /= trim(print_policy_format_clause) .or. &
            trim(value%output_clause) /= trim(print_policy_output_clause) .or. &
            value%statement_page /= print_policy_statement_page .or. &
            value%format_page /= print_policy_format_page .or. &
            value%output_page /= print_policy_output_page .or. &
            trim(value%source_hash) /= trim(print_policy_source_hash)) then
            message = 'invalid-print-policy-source'
            print_stmt_validate = .false.
            return
        end if
        print_stmt_validate = source_span_validate(value%span, message)
    end function print_stmt_validate

    subroutine print_stmt_to_sx(value, output, ok, message)
        type(print_stmt_t), intent(in) :: value
        character(len=*), intent(out) :: output
        logical, intent(out) :: ok
        character(len=*), intent(out) :: message
        character(len=2048) :: span_sx
        character(len=32) :: output_value_s, output_2_value_s, output_3_value_s
        character(len=32) :: output_4_value_s, output_5_value_s, output_6_value_s
        character(len=32) :: output_count_s
        character(len=32) :: statement_page_s
        character(len=32) :: format_page_s, output_page_s

        output = ''
        ok = .false.
        message = ''
        if (.not. print_stmt_validate(value, message)) return
        call source_span_to_sx(value%span, span_sx, ok, message)
        if (.not. ok) return
        write (output_value_s, '(i0)') value%output_value
        write (output_2_value_s, '(i0)') value%output_2_value
        write (output_3_value_s, '(i0)') value%output_3_value
        write (output_4_value_s, '(i0)') value%output_4_value
        write (output_5_value_s, '(i0)') value%output_5_value
        write (output_6_value_s, '(i0)') value%output_6_value
        write (output_count_s, '(i0)') value%output_count
        write (statement_page_s, '(i0)') value%statement_page
        write (format_page_s, '(i0)') value%format_page
        write (output_page_s, '(i0)') value%output_page
        if (value%output_count == 1_int64) then
            output = '(print-stmt (format-kind '//trim(value%format_kind)// &
                ') (format-value '//trim(value%format_value)//') (output-kind '// &
                trim(value%output_kind)//') (output-value '//trim(output_value_s)// &
                ') (span '//trim(span_sx)//') (statement-rule '// &
                trim(value%statement_rule)//') (format-rule '//trim(value%format_rule)// &
                ') (output-rule '//trim(value%output_rule)//') (source-document '// &
                trim(value%source_document)//') (statement-clause '// &
                trim(value%statement_clause)//') (format-clause '//trim(value%format_clause)// &
                ') (output-clause '//trim(value%output_clause)//') (statement-page '// &
                trim(statement_page_s)//') (format-page '//trim(format_page_s)// &
                ') (output-page '//trim(output_page_s)//') (source-hash '// &
                trim(value%source_hash)//'))'
        else if (value%output_count == 2_int64) then
            output = '(print-stmt (format-kind '//trim(value%format_kind)// &
                ') (format-value '//trim(value%format_value)//') (output-kind '// &
                trim(value%output_kind)//') (output-value '//trim(output_value_s)// &
                ') (output-count '//trim(output_count_s)//') (output-kind-2 '// &
                trim(value%output_2_kind)//') (output-value-2 '// &
                trim(output_2_value_s)//') (output-rule-2 '//trim(value%output_2_rule)// &
                ') (span '//trim(span_sx)//') (statement-rule '// &
                trim(value%statement_rule)//') (format-rule '//trim(value%format_rule)// &
                ') (output-rule '//trim(value%output_rule)//') (source-document '// &
                trim(value%source_document)//') (statement-clause '// &
                trim(value%statement_clause)//') (format-clause '//trim(value%format_clause)// &
                ') (output-clause '//trim(value%output_clause)//') (statement-page '// &
                trim(statement_page_s)//') (format-page '//trim(format_page_s)// &
                ') (output-page '//trim(output_page_s)//') (source-hash '// &
                trim(value%source_hash)//'))'
        else if (value%output_count == 3_int64) then
            output = '(print-stmt (format-kind '//trim(value%format_kind)// &
                ') (format-value '//trim(value%format_value)//') (output-kind '// &
                trim(value%output_kind)//') (output-value '//trim(output_value_s)// &
                ') (output-count '//trim(output_count_s)//') (output-kind-2 '// &
                trim(value%output_2_kind)//') (output-value-2 '// &
                trim(output_2_value_s)//') (output-rule-2 '//trim(value%output_2_rule)// &
                ') (output-kind-3 '//trim(value%output_3_kind)// &
                ') (output-value-3 '//trim(output_3_value_s)//') (output-rule-3 '// &
                trim(value%output_3_rule)//') (span '//trim(span_sx)//') '// &
                '(statement-rule '//trim(value%statement_rule)//') (format-rule '// &
                trim(value%format_rule)//') (output-rule '//trim(value%output_rule)// &
                ') (source-document '//trim(value%source_document)//') '// &
                '(statement-clause '//trim(value%statement_clause)//') '// &
                '(format-clause '//trim(value%format_clause)//') (output-clause '// &
                trim(value%output_clause)//') (statement-page '//trim(statement_page_s)// &
                ') (format-page '//trim(format_page_s)//') (output-page '// &
                trim(output_page_s)//') (source-hash '//trim(value%source_hash)//'))'
        else if (value%output_count == 4_int64) then
            output = '(print-stmt (format-kind '//trim(value%format_kind)// &
                ') (format-value '//trim(value%format_value)//') (output-kind '// &
                trim(value%output_kind)//') (output-value '//trim(output_value_s)// &
                ') (output-count '//trim(output_count_s)//') (output-kind-2 '// &
                trim(value%output_2_kind)//') (output-value-2 '//trim(output_2_value_s)// &
                ') (output-rule-2 '//trim(value%output_2_rule)//') (output-kind-3 '// &
                trim(value%output_3_kind)//') (output-value-3 '//trim(output_3_value_s)// &
                ') (output-rule-3 '//trim(value%output_3_rule)//') (output-kind-4 '// &
                trim(value%output_4_kind)//') (output-value-4 '//trim(output_4_value_s)// &
                ') (output-rule-4 '//trim(value%output_4_rule)//') (span '// &
                trim(span_sx)//') (statement-rule '//trim(value%statement_rule)// &
                ') (format-rule '//trim(value%format_rule)//') (output-rule '// &
                trim(value%output_rule)//') (source-document '//trim(value%source_document)// &
                ') (statement-clause '//trim(value%statement_clause)//') (format-clause '// &
                trim(value%format_clause)//') (output-clause '//trim(value%output_clause)// &
                ') (statement-page '//trim(statement_page_s)//') (format-page '// &
                trim(format_page_s)//') (output-page '//trim(output_page_s)// &
                ') (source-hash '//trim(value%source_hash)//'))'
        else if (value%output_count == 5_int64) then
            output = '(print-stmt (format-kind '//trim(value%format_kind)// &
                ') (format-value '//trim(value%format_value)//') (output-kind '// &
                trim(value%output_kind)//') (output-value '//trim(output_value_s)// &
                ') (output-count '//trim(output_count_s)//') (output-kind-2 '// &
                trim(value%output_2_kind)//') (output-value-2 '//trim(output_2_value_s)// &
                ') (output-rule-2 '//trim(value%output_2_rule)//') (output-kind-3 '// &
                trim(value%output_3_kind)//') (output-value-3 '//trim(output_3_value_s)// &
                ') (output-rule-3 '//trim(value%output_3_rule)//') (output-kind-4 '// &
                trim(value%output_4_kind)//') (output-value-4 '//trim(output_4_value_s)// &
                ') (output-rule-4 '//trim(value%output_4_rule)//') (output-kind-5 '// &
                trim(value%output_5_kind)//') (output-value-5 '//trim(output_5_value_s)// &
                ') (output-rule-5 '//trim(value%output_5_rule)//') (span '// &
                trim(span_sx)//') (statement-rule '//trim(value%statement_rule)// &
                ') (format-rule '//trim(value%format_rule)//') (output-rule '// &
                trim(value%output_rule)//') (source-document '//trim(value%source_document)// &
                ') (statement-clause '//trim(value%statement_clause)//') (format-clause '// &
                trim(value%format_clause)//') (output-clause '//trim(value%output_clause)// &
                ') (statement-page '//trim(statement_page_s)//') (format-page '// &
                trim(format_page_s)//') (output-page '//trim(output_page_s)// &
                ') (source-hash '//trim(value%source_hash)//'))'
        else
            output = '(print-stmt (format-kind '//trim(value%format_kind)// &
                ') (format-value '//trim(value%format_value)//') (output-kind '// &
                trim(value%output_kind)//') (output-value '//trim(output_value_s)// &
                ') (output-count '//trim(output_count_s)//') (output-kind-2 '// &
                trim(value%output_2_kind)//') (output-value-2 '//trim(output_2_value_s)// &
                ') (output-rule-2 '//trim(value%output_2_rule)//') (output-kind-3 '// &
                trim(value%output_3_kind)//') (output-value-3 '//trim(output_3_value_s)// &
                ') (output-rule-3 '//trim(value%output_3_rule)//') (output-kind-4 '// &
                trim(value%output_4_kind)//') (output-value-4 '//trim(output_4_value_s)// &
                ') (output-rule-4 '//trim(value%output_4_rule)//') (output-kind-5 '// &
                trim(value%output_5_kind)//') (output-value-5 '//trim(output_5_value_s)// &
                ') (output-rule-5 '//trim(value%output_5_rule)//') (output-kind-6 '// &
                trim(value%output_6_kind)//') (output-value-6 '//trim(output_6_value_s)// &
                ') (output-rule-6 '//trim(value%output_6_rule)//') (span '// &
                trim(span_sx)//') (statement-rule '//trim(value%statement_rule)// &
                ') (format-rule '//trim(value%format_rule)//') (output-rule '// &
                trim(value%output_rule)//') (source-document '//trim(value%source_document)// &
                ') (statement-clause '//trim(value%statement_clause)//') (format-clause '// &
                trim(value%format_clause)//') (output-clause '//trim(value%output_clause)// &
                ') (statement-page '//trim(statement_page_s)//') (format-page '// &
                trim(format_page_s)//') (output-page '//trim(output_page_s)// &
                ') (source-hash '//trim(value%source_hash)//'))'
        end if
        ok = .true.
    end subroutine print_stmt_to_sx

end module frontend_print_policy_generated
'''


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("schema", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        generated = render(args.schema.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        parser.error(str(error))
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "frontend_print_policy_generated.f90").write_text(
        generated, encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
