#!/usr/bin/env python3
"""Generate the bounded v2 program-unit envelope policy."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


SCHEMA = re.compile(
    r"\(schema\s+frontend-program-unit-v2-envelope-v0\s+"
    r"\(envelope\s+(program-unit-v2)\)\s+"
    r"\(execution-part\s+(execution-part)\)\s+"
    r"\(source-rule\s+(R509)\s+(J3-24-007)\s+(5)\s+(98)\s+([^\s()]+)\)\)\s*\Z"
)


def parse(source: str) -> tuple[str, str, str, str, str, str, str]:
    match = SCHEMA.fullmatch(source.strip())
    if match is None:
        raise ValueError("invalid program-unit-v2 envelope schema")
    return match.groups()


def render(values: tuple[str, str, str, str, str, str, str]) -> str:
    envelope, child, rule, document, clause, page, source_hash = values
    return f"""! Generated by tools/generate_program_unit_v2_envelope.py. Origin: MECHANICAL.
module frontend_program_unit_v2_envelope_generated
    use, intrinsic :: iso_fortran_env, only: int64
    implicit none
    private

    character(len=32), parameter, public :: program_unit_v2_envelope_kind = '{envelope}'
    character(len=32), parameter, public :: program_unit_v2_execution_part_kind = '{child}'
    character(len=32), parameter, public :: program_unit_v2_execution_part_source_rule = '{rule}'
    character(len=128), parameter, public :: program_unit_v2_execution_part_document = '{document}'
    character(len=32), parameter, public :: program_unit_v2_execution_part_clause = '{clause}'
    integer(int64), parameter, public :: program_unit_v2_execution_part_page = {page}_int64
    character(len=128), parameter, public :: program_unit_v2_execution_part_source_hash = &
        '{source_hash}'

    type, public :: program_unit_v2_policy_t
        character(len=32) :: kind = ''
        character(len=32) :: source_rule = ''
        character(len=128) :: document = ''
        character(len=32) :: clause = ''
        integer(int64) :: page = 0_int64
        character(len=128) :: source_hash = ''
    end type program_unit_v2_policy_t

    type(program_unit_v2_policy_t), parameter, public :: &
        program_unit_v2_policy_table(1) = [ &
        program_unit_v2_policy_t('execution-part', 'R509', 'J3-24-007', '5', &
            98_int64, '1cf538329c57e4f617adb36f2c7cd91a5a5561c78bcce16ec96f7ff1a9979f') ]

    public :: program_unit_v2_execution_part_policy_matches

contains

    logical function program_unit_v2_execution_part_policy_matches(kind)
        character(len=*), intent(in) :: kind

        program_unit_v2_execution_part_policy_matches = &
            trim(kind) == trim(program_unit_v2_policy_table(1)%kind)
    end function program_unit_v2_execution_part_policy_matches

end module frontend_program_unit_v2_envelope_generated
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("schema", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        generated = render(parse(args.schema.read_text(encoding="utf-8")))
    except (OSError, ValueError) as error:
        parser.error(str(error))
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "frontend_program_unit_v2_envelope_generated.f90").write_text(
        generated, encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
