#!/usr/bin/env python3
"""Generate the bounded R1033 assignment-statement policy."""

from pathlib import Path
import re
import sys


def main() -> int:
    source = Path(sys.argv[1]).read_text(encoding="utf-8").strip()
    match = re.fullmatch(
        r"\(schema frontend-assignment-policy-v0\s+"
        r"\(policy assignment-stmt assignment-stmt (R\d+)\)\s+"
        r"\(token assignment (=)\)\s+"
        r"\(expression integer-literal (1)\)\)", source
    )
    if match is None:
        raise SystemExit("invalid assignment policy schema")
    output = Path(sys.argv[2])
    output.mkdir(parents=True, exist_ok=True)
    (output / "frontend_assignment_policy_generated.f90").write_text(
        "! Generated by tools/generate_assignment_policy.py. Origin: MECHANICAL.\n"
        "module frontend_assignment_policy_generated\n"
        "    implicit none\n"
        "    private\n"
        "    character(len=*), parameter, public :: assignment_policy_lhs = 'assignment-stmt'\n"
        f"    character(len=*), parameter, public :: assignment_policy_source_rule = '{match.group(1)}'\n"
        "    character(len=*), parameter, public :: assignment_policy_operator = '='\n"
        "    character(len=*), parameter, public :: assignment_policy_integer_literal = '1'\n"
        "end module frontend_assignment_policy_generated\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
