#!/usr/bin/env python3
"""Generate the bounded typed-declaration acceptance policy."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


SCHEMA = re.compile(
    r"\(schema\s+frontend-typed-declaration-policy-v0\s+"
    r"\(policy\s+declaration-line\s+(exact)\)\s+"
    r"\(cardinality\s+program-declaration\s+(exact)\s+(\d+)\)\s+"
    r"\(cardinality\s+typed-variable-declaration\s+(exact)\s+(\d+)\)\s*\)\s*\Z"
)


def render(source: str) -> str:
    match = SCHEMA.fullmatch(source.strip())
    if match is None:
        raise ValueError("invalid typed-declaration policy schema")
    mode = match.group(1)
    program_declaration_count = match.group(3)
    typed_variable_declaration_count = match.group(5)
    return "\n".join([
        "! Generated by tools/generate_typed_declaration_policy.py. Origin: MECHANICAL.",
        "module frontend_typed_declaration_policy_generated",
        "    use, intrinsic :: iso_fortran_env, only: int64",
        "    implicit none",
        "    private",
        "",
        "    character(len=*), parameter, public :: &",
        "        typed_declaration_policy_mode = '%s'" % mode,
        "    integer(int64), parameter, public :: &",
        "        typed_program_declaration_cardinality = %s_int64" % program_declaration_count,
        "    integer(int64), parameter, public :: &",
        "        typed_variable_declaration_cardinality = %s_int64" % typed_variable_declaration_count,
        "",
        "    public :: typed_declaration_policy_matches",
        "",
        "contains",
        "",
        "    logical function typed_declaration_policy_matches(actual, expected)",
        "        character(len=*), intent(in) :: actual",
        "        character(len=*), intent(in) :: expected",
        "",
        "        typed_declaration_policy_matches = actual == trim(expected)",
        "    end function typed_declaration_policy_matches",
        "",
        "end module frontend_typed_declaration_policy_generated",
        "",
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("schema", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    try:
        generated = render(args.schema.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        parser.error(str(error))
    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "frontend_typed_declaration_policy_generated.f90").write_text(
        generated, encoding="utf-8"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
