#!/usr/bin/env python3
"""Generate the bounded R1033 assignment-statement policy."""

from pathlib import Path
import re
import sys


def main() -> int:
    source = Path(sys.argv[1]).read_text(encoding="utf-8").strip()
    match = re.fullmatch(
        r"\(schema frontend-assignment-policy-v0\s+"
        r"\(policy assignment-stmt assignment-stmt (R\d+)\)\s+"
        r"\(token assignment (=)\)\s+"
        r"\(expression integer-literal (1)\)\s+"
        r"\(binary-expression (add) (R\d+) (R\d+) (1) (2) (\+)\)\s+"
        r"\(binary-expression (subtract) (R\d+) (R\d+) (5) (3) (–)\)\s+"
        r"\(binary-expression (multiply) (R\d+) (R\d+) (2) (3) (\*)\)\s+"
        r"\(binary-expression (divide) (R\d+) (R\d+) (6) (2) (/)\)\)", source
    )
    if match is None:
        raise SystemExit("invalid assignment policy schema")
    output = Path(sys.argv[2])
    output.mkdir(parents=True, exist_ok=True)
    rows = [
        ("integer-literal", "", "", match.group(1), "1", "1", "", ""),
        (match.group(4), match.group(5), match.group(6), match.group(1),
            f"{match.group(7)} {match.group(9)} {match.group(8)}", match.group(7),
            match.group(8), match.group(9)),
        ("subtract", match.group(11), match.group(12), match.group(1),
            f"{match.group(13)} {match.group(15)} {match.group(14)}", match.group(13),
            match.group(14), match.group(15)),
        ("multiply", match.group(17), match.group(18), match.group(1),
            f"{match.group(19)} {match.group(21)} {match.group(20)}", match.group(19),
            match.group(20), match.group(21)),
        ("divide", match.group(23), match.group(24), match.group(1),
            f"{match.group(25)} {match.group(27)} {match.group(26)}", match.group(25),
            match.group(26), match.group(27)),
    ]
    row_text = "\n".join(
        "        assignment_policy_row_t('%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s')%s" % (
            *row, ", &" if index < len(rows) - 1 else ""
        )
        for index, row in enumerate(rows)
    )
    (output / "frontend_assignment_policy_generated.f90").write_text(
        "! Generated by tools/generate_assignment_policy.py. Origin: MECHANICAL.\n"
        "module frontend_assignment_policy_generated\n"
        "    implicit none\n"
        "    private\n"
        "    character(len=*), parameter, public :: assignment_policy_lhs = 'assignment-stmt'\n"
        f"    character(len=*), parameter, public :: assignment_policy_source_rule = '{match.group(1)}'\n"
        "    character(len=*), parameter, public :: assignment_policy_operator = '='\n"
        "    type, public :: assignment_policy_row_t\n"
        "        character(len=16) :: expression_kind\n"
        "        character(len=16) :: expression_rule\n"
        "        character(len=16) :: operator_rule\n"
        "        character(len=16) :: source_rule\n"
        "        character(len=32) :: source_spelling\n"
        "        character(len=16) :: left_operand\n"
        "        character(len=16) :: right_operand\n"
        "        character(len=8) :: operator\n"
        "    end type assignment_policy_row_t\n"
        "    type(assignment_policy_row_t), parameter, public :: assignment_policy_rows(5) = [ &\n"
        f"{row_text} &\n"
        "    ]\n"
        "    integer, parameter, public :: assignment_policy_row_count = 5\n"
        "    integer, parameter, public :: assignment_policy_source_page = 155\n"
        "end module frontend_assignment_policy_generated\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
